# Generated by Django 5.2.5 on 2025-08-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Unknown", max_length=200)),
                ("location", models.CharField(default="Not Specified", max_length=200)),
                ("industry", models.CharField(default="General", max_length=100)),
            ],
        ),
    ]
