# Generated by Django 5.2.5 on 2025-08-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="industry",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
