# Generated by Django 5.2.5 on 2025-08-28 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "enterprise_app",
            "0002_enterprise_is_active_alter_enterprise_industry_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="industry",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="location",
            field=models.CharField(default="Not specified", max_length=100),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(default="Not specified", max_length=100)),
                ("industry", models.CharField(default="General", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="enterprise_app.enterprise",
                    ),
                ),
            ],
        ),
    ]
