# Generated by Django 5.2.5 on 2025-08-29 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise_app", "0003_enterprise_created_on_enterprise_updated_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enterprise_app.enterprise",
            ),
        ),
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circles",
                        to="enterprise_app.enterprise",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circles",
                        to="enterprise_app.region",
                    ),
                ),
            ],
        ),
    ]
