# Generated by Django 5.2.5 on 2025-09-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise_app", "0006_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="industry",
            field=models.CharField(default="General", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="location",
            field=models.CharField(
                default="Not specified", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="updated_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name="circle",
            unique_together={("name", "enterprise", "region", "location", "industry")},
        ),
        migrations.AlterUniqueTogether(
            name="cluster",
            unique_together={
                ("name", "enterprise", "region", "circle", "location", "industry")
            },
        ),
        migrations.AlterUniqueTogether(
            name="enterprise",
            unique_together={("name", "location", "industry")},
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together={("name", "location", "industry", "enterprise")},
        ),
        migrations.AlterUniqueTogether(
            name="store",
            unique_together={
                (
                    "name",
                    "enterprise",
                    "region",
                    "circle",
                    "cluster",
                    "location",
                    "industry",
                )
            },
        ),
    ]
