# Generated by Django 5.2.5 on 2025-09-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise_app", "0007_alter_region_industry_alter_region_location_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enterprise",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="circle",
            unique_together={("name", "enterprise", "region")},
        ),
        migrations.AlterUniqueTogether(
            name="cluster",
            unique_together={("name", "enterprise", "region", "circle")},
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together={("name", "enterprise")},
        ),
        migrations.AlterUniqueTogether(
            name="store",
            unique_together={("name", "enterprise", "region", "circle", "cluster")},
        ),
        migrations.AddField(
            model_name="circle",
            name="deleted_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cluster",
            name="deleted_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="deleted_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="deleted_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="deleted_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="circle",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="industry",
            field=models.CharField(
                blank=True, default="General", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="location",
            field=models.CharField(
                blank=True, default="Unknown", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="store",
            name="industry",
            field=models.CharField(
                blank=True, default="General", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="location",
            field=models.CharField(
                blank=True, default="Unknown", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="store",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="circle",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="circle",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="circle",
            name="location",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="location",
        ),
        migrations.RemoveField(
            model_name="region",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="region",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="region",
            name="location",
        ),
        migrations.RemoveField(
            model_name="store",
            name="created_on",
        ),
    ]
