# Generated by Django 5.2.5 on 2025-09-01 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise_app", "0008_alter_enterprise_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="circle",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="cluster",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="store",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="location",
        ),
        migrations.AddField(
            model_name="circle",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cluster",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enterprise",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="store",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="circle",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circles",
                to="enterprise_app.enterprise",
            ),
        ),
        migrations.AlterField(
            model_name="circle",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circles",
                to="enterprise_app.region",
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="circle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clusters",
                to="enterprise_app.circle",
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clusters",
                to="enterprise_app.enterprise",
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clusters",
                to="enterprise_app.region",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="enterprise_app.enterprise",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="circle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to="enterprise_app.circle",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to="enterprise_app.cluster",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to="enterprise_app.enterprise",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to="enterprise_app.region",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="circle",
            unique_together={("enterprise", "region", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="cluster",
            unique_together={("enterprise", "region", "circle", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together={("enterprise", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="store",
            unique_together={("enterprise", "region", "circle", "cluster", "name")},
        ),
    ]
