# Generated by Django 5.2.5 on 2025-09-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise_app", "0009_alter_circle_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="store",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="store",
            name="location",
        ),
    ]
