# Generated by Django 5.2.5 on 2025-09-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise_app", "0010_role_remove_store_industry_remove_store_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="created_at",
            new_name="created_on",
        ),
        migrations.RenameField(
            model_name="role",
            old_name="updated_at",
            new_name="updated_on",
        ),
        migrations.AddField(
            model_name="role",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
