# Generated by Django 5.2.5 on 2025-09-03 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise_app", "0013_userstorerole"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="enterprise_app.role",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="enterprise_app.store",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserStoreRole",
        ),
    ]
