# Generated by Django 5.2.5 on 2025-09-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise_app", "0014_user_role_user_store_delete_userstorerole"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
