# Generated by Django 5.2.5 on 2025-09-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise_app", "0018_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
