# Generated by Django 5.2.5 on 2025-09-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise_app", "0019_alter_user_is_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_verified",
            new_name="otp_verification",
        ),
    ]
